layout_spectrum: 0.9097808
typography_spectrum: 0.6247892
color:
  lightness: 0.108769
  brandStrength: 0.05455859
  saturation: 0.7478921
  rhythmicContrast: 0.6315346
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Someday Group
